# Project: project1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = jarvis.o calculator.o Quiz.o
LINKOBJ  = jarvis.o calculator.o Quiz.o
LIBS     = -L"E:/opt/Devc++/devc++/Dev-Cpp/MinGW64/lib" -L"E:/opt/Devc++/devc++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"E:/opt/Devc++/devc++/Dev-Cpp/MinGW64/include" -I"E:/opt/Devc++/devc++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/opt/Devc++/devc++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"E:/opt/Devc++/devc++/Dev-Cpp/MinGW64/include" -I"E:/opt/Devc++/devc++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/opt/Devc++/devc++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"E:/opt/Devc++/devc++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = jarvis.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

jarvis.o: jarvis.c
	$(CC) -c jarvis.c -o jarvis.o $(CFLAGS)

calculator.o: calculator.c
	$(CC) -c calculator.c -o calculator.o $(CFLAGS)

Quiz.o: Quiz.c
	$(CC) -c Quiz.c -o Quiz.o $(CFLAGS)
